#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @Filename: suffix_dict
# @Date: 2016-12-03
# @Author: Mark Wang
# @Email: wangyouan@gmial.com


suffix_dict = {'ComNum1k': ['prosComNum1k', 'consComNum1k', 'advComNum1k', 'allComNum1k'],
               'Num1k': ['prosNum1k', 'allNum1k', 'advNum1k', 'consNum1k'],
               'PM_ComNCh_avgAll1k': ['prosPM_prosComNCh_avgAll1k',
                                      'consPM_consComNCh_avgAll1k',
                                      'advPM_advComNCh_avgAll1k',
                                      'allPM_allComNCh_avgAll1k',
                                      'ProsConsPM_allComNCh_avgAll1k',
                                      'ProsConsAdvPM_allComNCh_avgAll1k'],
               'PM_ComNCh_avgCom1k': ['prosPM_prosComNCh_avgCom1k',
                                      'consPM_consComNCh_avgCom1k',
                                      'advPM_advComNCh_avgCom1k',
                                      'allPM_allComNCh_avgCom1k',
                                      'ProsConsPM_allComNCh_avgCom1k',
                                      'ProsConsAdvPM_allComNCh_avgCom1k'],
               'PM_ComNCh_sum1k': ['prosPM_prosComNCh_sum1k',
                                   'consPM_consComNCh_sum1k',
                                   'advPM_advComNCh_sum1k',
                                   'allPM_allComNCh_sum1k',
                                   'ProsConsPM_allComNCh_sum1k',
                                   'ProsConsAdvPM_allComNCh_sum1k'],
               'PM_ComNCom_avgAll1k': ['prosPM_prosComNCom_avgAll1k',
                                       'consPM_consComNCom_avgAll1k',
                                       'advPM_advComNCom_avgAll1k',
                                       'allPM_allComNCom_avgAll1k',
                                       'ProsConsPM_allComNCom_avgAll1k',
                                       'ProsConsAdvPM_allComNCom_avAll1k'],
               'PM_ComNCom_avgCom1k': ['prosPM_prosComNCom_avgCom1k',
                                       'consPM_consComNCom_avgCom1k',
                                       'advPM_advComNCom_avgCom1k',
                                       'allPM_allComNCom_avgCom1k',
                                       'ProsConsPM_allComNCom_avgCom1k',
                                       'ProsConsAdvPM_allComNCom_avCom1k'],
               'PM_ComNCom_sum1k': ['prosPM_prosComNCom_sum1k',
                                    'consPM_consComNCom_sum1k',
                                    'advPM_advComNCom_sum1k',
                                    'allPM_allComNCom_sum1k',
                                    'ProsConsPM_allComNCom_sum1k',
                                    'ProsConsAdvPM_allComNCom_sum1k'],
               'PM_ComNSt_avgAll1k': ['prosPM_prosComNSt_avgAll1k',
                                      'consPM_consComNSt_avgAll1k',
                                      'advPM_advComNSt_avgAll1k',
                                      'allPM_allComNSt_avgAll1k',
                                      'ProsConsPM_allComNSt_avgAll1k',
                                      'ProsConsAdvPM_allComNSt_avgAll1k'],
               'PM_ComNSt_avgCom1k': ['prosPM_prosComNSt_avgCom1k',
                                      'consPM_consComNSt_avgCom1k',
                                      'advPM_advComNSt_avgCom1k',
                                      'allPM_allComNSt_avgCom1k',
                                      'ProsConsPM_allComNSt_avgCom1k',
                                      'ProsConsAdvPM_allComNSt_avgCom1k'],
               'PM_ComNSt_sum1k': ['prosPM_prosComNSt_sum1k',
                                   'consPM_consComNSt_sum1k',
                                   'advPM_advComNSt_sum1k',
                                   'allPM_allComNSt_sum1k',
                                   'ProsConsPM_allComNSt_sum1k',
                                   'ProsConsAdvPM_allComNSt_sum1k'],
               'PM_ComNWd_avgAll1k': ['prosPM_prosComNWd_avgAll1k',
                                      'consPM_consComNWd_avgAll1k',
                                      'advPM_advComNWd_avgAll1k',
                                      'allPM_allComNWd_avgAll1k',
                                      'ProsConsPM_allComNWd_avgAll1k',
                                      'ProsConsAdvPM_allComNWd_avgAll1k'],
               'PM_ComNWd_avgCom1k': ['prosPM_prosComNWd_avgCom1k',
                                      'consPM_consComNWd_avgCom1k',
                                      'advPM_advComNWd_avgCom1k',
                                      'allPM_allComNWd_avgCom1k',
                                      'ProsConsPM_allComNWd_avgCom1k',
                                      'ProsConsAdvPM_allComNWd_avgCom1k'],
               'PM_ComNWd_sum1k': ['prosPM_prosComNWd_sum1k',
                                   'consPM_consComNWd_sum1k',
                                   'advPM_advComNWd_sum1k',
                                   'allPM_allComNWd_sum1k',
                                   'ProsConsPM_allComNWd_sum1k',
                                   'ProsConsAdvPM_allComNWd_sum1k'],
               'PM_NCh_avgAll1k': ['prosPM_prosComNCh_avgAll1k',
                                   'prosPM_prosNCh_avgAll1k',
                                   'consPM_consComNCh_avgAll1k',
                                   'consPM_consNCh_avgAll1k',
                                   'advPM_advComNCh_avgAll1k',
                                   'advPM_advNCh_avgAll1k',
                                   'allPM_allComNCh_avgAll1k',
                                   'allPM_allNCh_avgAll1k',
                                   'ProsConsPM_allComNCh_avgAll1k',
                                   'ProsConsPM_allNCh_avgAll1k',
                                   'ProsConsAdvPM_allComNCh_avgAll1k',
                                   'ProsConsAdvPM_allNCh_avgAll1k'],
               'PM_NCh_avgCom1k': ['prosPM_prosComNCh_avgCom1k',
                                   'prosPM_prosNCh_avgCom1k',
                                   'consPM_consComNCh_avgCom1k',
                                   'consPM_consNCh_avgCom1k',
                                   'advPM_advComNCh_avgCom1k',
                                   'advPM_advNCh_avgCom1k',
                                   'allPM_allComNCh_avgCom1k',
                                   'allPM_allNCh_avgCom1k',
                                   'ProsConsPM_allComNCh_avgCom1k',
                                   'ProsConsPM_allNCh_avgCom1k',
                                   'ProsConsAdvPM_allComNCh_avgCom1k',
                                   'ProsConsAdvPM_allNCh_avgCom1k'],
               'PM_NCh_sum1k': ['prosPM_prosComNCh_sum1k',
                                'prosPM_prosNCh_sum1k',
                                'consPM_consComNCh_sum1k',
                                'consPM_consNCh_sum1k',
                                'advPM_advComNCh_sum1k',
                                'advPM_advNCh_sum1k',
                                'allPM_allComNCh_sum1k',
                                'allPM_allNCh_sum1k',
                                'ProsConsPM_allComNCh_sum1k',
                                'ProsConsPM_allNCh_sum1k',
                                'ProsConsAdvPM_allComNCh_sum1k',
                                'ProsConsAdvPM_allNCh_sum1k'],
               'PM_NCom_avgAll1k': ['prosPM_prosComNCom_avgAll1k',
                                    'prosPM_prosNCom_avgAll1k',
                                    'consPM_consComNCom_avgAll1k',
                                    'consPM_consNCom_avgAll1k',
                                    'advPM_advComNCom_avgAll1k',
                                    'advPM_advNCom_avgAll1k',
                                    'allPM_allComNCom_avgAll1k',
                                    'allPM_allNCom_avgAll1k',
                                    'ProsConsPM_allComNCom_avgAll1k',
                                    'ProsConsPM_allNCom_avgAll1k',
                                    'ProsConsAdvPM_allNCom_avgAll1k'],
               'PM_NCom_avgCom1k': ['prosPM_prosComNCom_avgCom1k',
                                    'prosPM_prosNCom_avgCom1k',
                                    'consPM_consComNCom_avgCom1k',
                                    'consPM_consNCom_avgCom1k',
                                    'advPM_advComNCom_avgCom1k',
                                    'advPM_advNCom_avgCom1k',
                                    'allPM_allComNCom_avgCom1k',
                                    'allPM_allNCom_avgCom1k',
                                    'ProsConsPM_allComNCom_avgCom1k',
                                    'ProsConsPM_allNCom_avgCom1k',
                                    'ProsConsAdvPM_allNCom_avgCom1k'],
               'PM_NCom_sum1k': ['prosPM_prosComNCom_sum1k',
                                 'prosPM_prosNCom_sum1k',
                                 'consPM_consComNCom_sum1k',
                                 'consPM_consNCom_sum1k',
                                 'advPM_advComNCom_sum1k',
                                 'advPM_advNCom_sum1k',
                                 'allPM_allComNCom_sum1k',
                                 'allPM_allNCom_sum1k',
                                 'ProsConsPM_allComNCom_sum1k',
                                 'ProsConsPM_allNCom_sum1k',
                                 'ProsConsAdvPM_allComNCom_sum1k',
                                 'ProsConsAdvPM_allNCom_sum1k'],
               'PM_NSt_avgAll1k': ['prosPM_prosComNSt_avgAll1k',
                                   'prosPM_prosNSt_avgAll1k',
                                   'consPM_consComNSt_avgAll1k',
                                   'consPM_consNSt_avgAll1k',
                                   'advPM_advComNSt_avgAll1k',
                                   'advPM_advNSt_avgAll1k',
                                   'allPM_allComNSt_avgAll1k',
                                   'allPM_allNSt_avgAll1k',
                                   'ProsConsPM_allComNSt_avgAll1k',
                                   'ProsConsPM_allNSt_avgAll1k',
                                   'ProsConsAdvPM_allComNSt_avgAll1k',
                                   'ProsConsAdvPM_allNSt_avgAll1k'],
               'PM_NSt_avgCom1k': ['prosPM_prosComNSt_avgCom1k',
                                   'prosPM_prosNSt_avgCom1k',
                                   'consPM_consComNSt_avgCom1k',
                                   'consPM_consNSt_avgCom1k',
                                   'advPM_advComNSt_avgCom1k',
                                   'advPM_advNSt_avgCom1k',
                                   'allPM_allComNSt_avgCom1k',
                                   'allPM_allNSt_avgCom1k',
                                   'ProsConsPM_allComNSt_avgCom1k',
                                   'ProsConsPM_allNSt_avgCom1k',
                                   'ProsConsAdvPM_allComNSt_avgCom1k',
                                   'ProsConsAdvPM_allNSt_avgCom1k'],
               'PM_NSt_sum1k': ['prosPM_prosComNSt_sum1k',
                                'prosPM_prosNSt_sum1k',
                                'consPM_consComNSt_sum1k',
                                'consPM_consNSt_sum1k',
                                'advPM_advComNSt_sum1k',
                                'advPM_advNSt_sum1k',
                                'allPM_allComNSt_sum1k',
                                'allPM_allNSt_sum1k',
                                'ProsConsPM_allComNSt_sum1k',
                                'ProsConsPM_allNSt_sum1k',
                                'ProsConsAdvPM_allComNSt_sum1k',
                                'ProsConsAdvPM_allNSt_sum1k'],
               'PM_NWd_avgAll1k': ['prosPM_prosComNWd_avgAll1k',
                                   'prosPM_prosNWd_avgAll1k',
                                   'consPM_consComNWd_avgAll1k',
                                   'consPM_consNWd_avgAll1k',
                                   'advPM_advComNWd_avgAll1k',
                                   'advPM_advNWd_avgAll1k',
                                   'allPM_allComNWd_avgAll1k',
                                   'allPM_allNWd_avgAll1k',
                                   'ProsConsPM_allComNWd_avgAll1k',
                                   'ProsConsPM_allNWd_avgAll1k',
                                   'ProsConsAdvPM_allComNWd_avgAll1k',
                                   'ProsConsAdvPM_allNWd_avgAll1k'],
               'PM_NWd_avgCom1k': ['prosPM_prosComNWd_avgCom1k',
                                   'prosPM_prosNWd_avgCom1k',
                                   'consPM_consComNWd_avgCom1k',
                                   'consPM_consNWd_avgCom1k',
                                   'advPM_advComNWd_avgCom1k',
                                   'advPM_advNWd_avgCom1k',
                                   'allPM_allComNWd_avgCom1k',
                                   'allPM_allNWd_avgCom1k',
                                   'ProsConsPM_allComNWd_avgCom1k',
                                   'ProsConsPM_allNWd_avgCom1k',
                                   'ProsConsAdvPM_allComNWd_avgCom1k',
                                   'ProsConsAdvPM_allNWd_avgCom1k'],
               'PM_NWd_sum1k': ['prosPM_prosComNWd_sum1k',
                                'prosPM_prosNWd_sum1k',
                                'consPM_consComNWd_sum1k',
                                'consPM_consNWd_sum1k',
                                'advPM_advComNWd_sum1k',
                                'advPM_advNWd_sum1k',
                                'allPM_allComNWd_sum1k',
                                'allPM_allNWd_sum1k',
                                'ProsConsPM_allComNWd_sum1k',
                                'ProsConsPM_allNWd_sum1k',
                                'ProsConsAdvPM_allComNWd_sum1k',
                                'ProsConsAdvPM_allNWd_sum1k'],
               'PM_simple1k': ['prosPM_simple1k',
                               'consPM_simple1k',
                               'advPM_simple1k',
                               'allPM_simple1k',
                               'ProsConsPM_simple1k',
                               'ProsConsAdvPM_simple1k'],
               'P_ComNCh_avgAll1k': ['prosP_prosComNCh_avgAll1k',
                                     'consP_consComNCh_avgAll1k',
                                     'advP_advComNCh_avgAll1k',
                                     'allP_allComNCh_avgAll1k',
                                     'ProsConsP_allComNCh_avgAll1k',
                                     'ProsConsAdvP_allComNCh_avgAll1k'],
               'P_ComNCh_avgCom1k': ['prosP_prosComNCh_avgCom1k',
                                     'consP_consComNCh_avgCom1k',
                                     'advP_advComNCh_avgCom1k',
                                     'allP_allComNCh_avgCom1k',
                                     'ProsConsP_allComNCh_avgCom1k',
                                     'ProsConsAdvP_allComNCh_avgCom1k'],
               'P_ComNCh_sum1k': ['prosP_prosComNCh_sum1k',
                                  'consP_consComNCh_sum1k',
                                  'advP_advComNCh_sum1k',
                                  'allP_allComNCh_sum1k',
                                  'ProsConsP_allComNCh_sum1k',
                                  'ProsConsAdvP_allComNCh_sum1k'],
               'P_ComNCom_avgAll1k': ['prosP_prosComNCom_avgAll1k',
                                      'consP_consComNCom_avgAll1k',
                                      'advP_advComNCom_avgAll1k',
                                      'allP_allComNCom_avgAll1k',
                                      'ProsConsP_allComNCom_avgAll1k',
                                      'ProsConsAdvP_allComNCom_avgAll1k'],
               'P_ComNCom_avgCom1k': ['prosP_prosComNCom_avgCom1k',
                                      'consP_consComNCom_avgCom1k',
                                      'advP_advComNCom_avgCom1k',
                                      'allP_allComNCom_avgCom1k',
                                      'ProsConsP_allComNCom_avgCom1k',
                                      'ProsConsAdvP_allComNCom_avgCom1k'],
               'P_ComNCom_sum1k': ['prosP_prosComNCom_sum1k',
                                   'consP_consComNCom_sum1k',
                                   'advP_advComNCom_sum1k',
                                   'allP_allComNCom_sum1k',
                                   'ProsConsP_allComNCom_sum1k',
                                   'ProsConsAdvP_allComNCom_sum1k'],
               'P_ComNSt_avgAll1k': ['prosP_prosComNSt_avgAll1k',
                                     'consP_consComNSt_avgAll1k',
                                     'advP_advComNSt_avgAll1k',
                                     'allP_allComNSt_avgAll1k',
                                     'ProsConsP_allComNSt_avgAll1k',
                                     'ProsConsAdvP_allComNSt_avgAll1k'],
               'P_ComNSt_avgCom1k': ['prosP_prosComNSt_avgCom1k',
                                     'consP_consComNSt_avgCom1k',
                                     'advP_advComNSt_avgCom1k',
                                     'allP_allComNSt_avgCom1k',
                                     'ProsConsP_allComNSt_avgCom1k',
                                     'ProsConsAdvP_allComNSt_avgCom1k'],
               'P_ComNSt_sum1k': ['prosP_prosComNSt_sum1k',
                                  'consP_consComNSt_sum1k',
                                  'advP_advComNSt_sum1k',
                                  'allP_allComNSt_sum1k',
                                  'ProsConsP_allComNSt_sum1k',
                                  'ProsConsAdvP_allComNSt_sum1k'],
               'P_ComNWd_avgAll1k': ['prosP_prosComNWd_avgAll1k',
                                     'consP_consComNWd_avgAll1k',
                                     'advP_advComNWd_avgAll1k',
                                     'allP_allComNWd_avgAll1k',
                                     'ProsConsP_allComNWd_avgAll1k',
                                     'ProsConsAdvP_allComNWd_avgAll1k'],
               'P_ComNWd_avgCom1k': ['prosP_prosComNWd_avgCom1k',
                                     'consP_consComNWd_avgCom1k',
                                     'advP_advComNWd_avgCom1k',
                                     'allP_allComNWd_avgCom1k',
                                     'ProsConsP_allComNWd_avgCom1k',
                                     'ProsConsAdvP_allComNWd_avgCom1k'],
               'P_ComNWd_sum1k': ['prosP_prosComNWd_sum1k',
                                  'consP_consComNWd_sum1k',
                                  'advP_advComNWd_sum1k',
                                  'allP_allComNWd_sum1k',
                                  'ProsConsP_allComNWd_sum1k',
                                  'ProsConsAdvP_allComNWd_sum1k'],
               'P_NCh_avgAll1k': ['prosP_prosComNCh_avgAll1k',
                                  'prosP_prosNCh_avgAll1k',
                                  'consP_consComNCh_avgAll1k',
                                  'consP_consNCh_avgAll1k',
                                  'advP_advComNCh_avgAll1k',
                                  'advP_advNCh_avgAll1k',
                                  'allP_allComNCh_avgAll1k',
                                  'allP_allNCh_avgAll1k',
                                  'ProsConsP_allComNCh_avgAll1k',
                                  'ProsConsP_allNCh_avgAll1k',
                                  'ProsConsAdvP_allComNCh_avgAll1k',
                                  'ProsConsAdvP_allNCh_avgAll1k'],
               'P_NCh_avgCom1k': ['prosP_prosComNCh_avgCom1k',
                                  'prosP_prosNCh_avgCom1k',
                                  'consP_consComNCh_avgCom1k',
                                  'consP_consNCh_avgCom1k',
                                  'advP_advComNCh_avgCom1k',
                                  'advP_advNCh_avgCom1k',
                                  'allP_allComNCh_avgCom1k',
                                  'allP_allNCh_avgCom1k',
                                  'ProsConsP_allComNCh_avgCom1k',
                                  'ProsConsP_allNCh_avgCom1k',
                                  'ProsConsAdvP_allComNCh_avgCom1k',
                                  'ProsConsAdvP_allNCh_avgCom1k'],
               'P_NCh_sum1k': ['prosP_prosComNCh_sum1k',
                               'prosP_prosNCh_sum1k',
                               'consP_consComNCh_sum1k',
                               'consP_consNCh_sum1k',
                               'advP_advComNCh_sum1k',
                               'advP_advNCh_sum1k',
                               'allP_allComNCh_sum1k',
                               'allP_allNCh_sum1k',
                               'ProsConsP_allComNCh_sum1k',
                               'ProsConsP_allNCh_sum1k',
                               'ProsConsAdvP_allComNCh_sum1k',
                               'ProsConsAdvP_allNCh_sum1k'],
               'P_NCom_avgAll1k': ['prosP_prosComNCom_avgAll1k',
                                   'prosP_prosNCom_avgAll1k',
                                   'consP_consComNCom_avgAll1k',
                                   'consP_consNCom_avgAll1k',
                                   'advP_advComNCom_avgAll1k',
                                   'advP_advNCom_avgAll1k',
                                   'allP_allComNCom_avgAll1k',
                                   'allP_allNCom_avgAll1k',
                                   'ProsConsP_allComNCom_avgAll1k',
                                   'ProsConsP_allNCom_avgAll1k',
                                   'ProsConsAdvP_allComNCom_avgAll1k',
                                   'ProsConsAdvP_allNCom_avgAll1k'],
               'P_NCom_avgCom1k': ['prosP_prosComNCom_avgCom1k',
                                   'prosP_prosNCom_avgCom1k',
                                   'consP_consComNCom_avgCom1k',
                                   'consP_consNCom_avgCom1k',
                                   'advP_advComNCom_avgCom1k',
                                   'advP_advNCom_avgCom1k',
                                   'allP_allComNCom_avgCom1k',
                                   'allP_allNCom_avgCom1k',
                                   'ProsConsP_allComNCom_avgCom1k',
                                   'ProsConsP_allNCom_avgCom1k',
                                   'ProsConsAdvP_allComNCom_avgCom1k',
                                   'ProsConsAdvP_allNCom_avgCom1k'],
               'P_NCom_sum1k': ['prosP_prosComNCom_sum1k',
                                'prosP_prosNCom_sum1k',
                                'consP_consComNCom_sum1k',
                                'consP_consNCom_sum1k',
                                'advP_advComNCom_sum1k',
                                'advP_advNCom_sum1k',
                                'allP_allComNCom_sum1k',
                                'allP_allNCom_sum1k',
                                'ProsConsP_allComNCom_sum1k',
                                'ProsConsP_allNCom_sum1k',
                                'ProsConsAdvP_allComNCom_sum1k',
                                'ProsConsAdvP_allNCom_sum1k'],
               'P_NSt_avgAll1k': ['prosP_prosComNSt_avgAll1k',
                                  'prosP_prosNSt_avgAll1k',
                                  'consP_consComNSt_avgAll1k',
                                  'consP_consNSt_avgAll1k',
                                  'advP_advComNSt_avgAll1k',
                                  'advP_advNSt_avgAll1k',
                                  'allP_allComNSt_avgAll1k',
                                  'allP_allNSt_avgAll1k',
                                  'ProsConsP_allComNSt_avgAll1k',
                                  'ProsConsP_allNSt_avgAll1k',
                                  'ProsConsAdvP_allComNSt_avgAll1k',
                                  'ProsConsAdvP_allNSt_avgAll1k'],
               'P_NSt_avgCom1k': ['prosP_prosComNSt_avgCom1k',
                                  'prosP_prosNSt_avgCom1k',
                                  'consP_consComNSt_avgCom1k',
                                  'consP_consNSt_avgCom1k',
                                  'advP_advComNSt_avgCom1k',
                                  'advP_advNSt_avgCom1k',
                                  'allP_allComNSt_avgCom1k',
                                  'allP_allNSt_avgCom1k',
                                  'ProsConsP_allComNSt_avgCom1k',
                                  'ProsConsP_allNSt_avgCom1k',
                                  'ProsConsAdvP_allComNSt_avgCom1k',
                                  'ProsConsAdvP_allNSt_avgCom1k'],
               'P_NSt_sum1k': ['prosP_prosComNSt_sum1k',
                               'prosP_prosNSt_sum1k',
                               'consP_consComNSt_sum1k',
                               'consP_consNSt_sum1k',
                               'advP_advComNSt_sum1k',
                               'advP_advNSt_sum1k',
                               'allP_allComNSt_sum1k',
                               'allP_allNSt_sum1k',
                               'ProsConsP_allComNSt_sum1k',
                               'ProsConsP_allNSt_sum1k',
                               'ProsConsAdvP_allComNSt_sum1k',
                               'ProsConsAdvP_allNSt_sum1k'],
               'P_NWd_avgAll1k': ['prosP_prosComNWd_avgAll1k',
                                  'prosP_prosNWd_avgAll1k',
                                  'consP_consComNWd_avgAll1k',
                                  'consP_consNWd_avgAll1k',
                                  'advP_advComNWd_avgAll1k',
                                  'advP_advNWd_avgAll1k',
                                  'allP_allComNWd_avgAll1k',
                                  'allP_allNWd_avgAll1k',
                                  'ProsConsP_allComNWd_avgAll1k',
                                  'ProsConsP_allNWd_avgAll1k',
                                  'ProsConsAdvP_allComNWd_avgAll1k',
                                  'ProsConsAdvP_allNWd_avgAll1k'],
               'P_NWd_avgCom1k': ['prosP_prosComNWd_avgCom1k',
                                  'prosP_prosNWd_avgCom1k',
                                  'consP_consComNWd_avgCom1k',
                                  'consP_consNWd_avgCom1k',
                                  'advP_advComNWd_avgCom1k',
                                  'advP_advNWd_avgCom1k',
                                  'allP_allComNWd_avgCom1k',
                                  'allP_allNWd_avgCom1k',
                                  'ProsConsP_allComNWd_avgCom1k',
                                  'ProsConsP_allNWd_avgCom1k',
                                  'ProsConsAdvP_allComNWd_avgCom1k',
                                  'ProsConsAdvP_allNWd_avgCom1k'],
               'P_NWd_sum1k': ['prosP_prosComNWd_sum1k',
                               'prosP_prosNWd_sum1k',
                               'consP_consComNWd_sum1k',
                               'consP_consNWd_sum1k',
                               'advP_advComNWd_sum1k',
                               'advP_advNWd_sum1k',
                               'allP_allComNWd_sum1k',
                               'allP_allNWd_sum1k',
                               'ProsConsP_allComNWd_sum1k',
                               'ProsConsP_allNWd_sum1k',
                               'ProsConsAdvP_allComNWd_sum1k',
                               'ProsConsAdvP_allNWd_sum1k'],
               'P_simple1k': ['prosP_simple1k',
                              'consP_simple1k',
                              'advP_simple1k',
                              'allP_simple1k',
                              'ProsConsP_simple1k',
                              'ProsConsAdvP_simple1k']}
independent_variables = ['prosNum1k', 'consNum1k', 'allNum1k', 'prosComNum1k', 'prosP_simple1k',
                         'prosP_prosComNCh_sum1k',
                         'prosP_prosComNCh_avgAll1k', 'prosP_prosComNCh_avgCom1k', 'prosP_prosComNCom_sum1k',
                         'prosP_prosComNCom_avgAll1k', 'prosP_prosComNCom_avgCom1k', 'prosP_prosComNSt_sum1k',
                         'prosP_prosComNSt_avgAll1k', 'prosP_prosComNSt_avgCom1k', 'prosP_prosComNWd_sum1k',
                         'prosP_prosComNWd_avgAll1k', 'prosP_prosComNWd_avgCom1k', 'prosP_prosNCh_sum1k',
                         'prosP_prosNCh_avgAll1k',
                         'prosP_prosNCh_avgCom1k', 'prosP_prosNCom_sum1k', 'prosP_prosNCom_avgAll1k',
                         'prosP_prosNCom_avgCom1k',
                         'prosP_prosNSt_sum1k', 'prosP_prosNSt_avgAll1k', 'prosP_prosNSt_avgCom1k',
                         'prosP_prosNWd_sum1k',
                         'prosP_prosNWd_avgAll1k', 'prosP_prosNWd_avgCom1k', 'prosPM_simple1k',
                         'prosPM_prosComNCh_sum1k',
                         'prosPM_prosComNCh_avgAll1k', 'prosPM_prosComNCh_avgCom1k', 'prosPM_prosComNCom_sum1k',
                         'prosPM_prosComNCom_avgAll1k', 'prosPM_prosComNCom_avgCom1k', 'prosPM_prosComNSt_sum1k',
                         'prosPM_prosComNSt_avgAll1k', 'prosPM_prosComNSt_avgCom1k', 'prosPM_prosComNWd_sum1k',
                         'prosPM_prosComNWd_avgAll1k', 'prosPM_prosComNWd_avgCom1k', 'prosPM_prosNCh_sum1k',
                         'prosPM_prosNCh_avgAll1k',
                         'prosPM_prosNCh_avgCom1k', 'prosPM_prosNCom_sum1k', 'prosPM_prosNCom_avgAll1k',
                         'prosPM_prosNCom_avgCom1k',
                         'prosPM_prosNSt_sum1k', 'prosPM_prosNSt_avgAll1k', 'prosPM_prosNSt_avgCom1k',
                         'prosPM_prosNWd_sum1k',
                         'prosPM_prosNWd_avgAll1k', 'prosPM_prosNWd_avgCom1k', 'consComNum1k', 'consP_simple1k',
                         'consP_consComNCh_sum1k', 'consP_consComNCh_avgAll1k', 'consP_consComNCh_avgCom1k',
                         'consP_consComNCom_sum1k',
                         'consP_consComNCom_avgAll1k', 'consP_consComNCom_avgCom1k', 'consP_consComNSt_sum1k',
                         'consP_consComNSt_avgAll1k', 'consP_consComNSt_avgCom1k', 'consP_consComNWd_sum1k',
                         'consP_consComNWd_avgAll1k', 'consP_consComNWd_avgCom1k', 'consP_consNCh_sum1k',
                         'consP_consNCh_avgAll1k',
                         'consP_consNCh_avgCom1k', 'consP_consNCom_sum1k', 'consP_consNCom_avgAll1k',
                         'consP_consNCom_avgCom1k',
                         'consP_consNSt_sum1k', 'consP_consNSt_avgAll1k', 'consP_consNSt_avgCom1k',
                         'consP_consNWd_sum1k',
                         'consP_consNWd_avgAll1k', 'consP_consNWd_avgCom1k', 'consPM_simple1k',
                         'consPM_consComNCh_sum1k',
                         'consPM_consComNCh_avgAll1k', 'consPM_consComNCh_avgCom1k', 'consPM_consComNCom_sum1k',
                         'consPM_consComNCom_avgAll1k', 'consPM_consComNCom_avgCom1k', 'consPM_consComNSt_sum1k',
                         'consPM_consComNSt_avgAll1k', 'consPM_consComNSt_avgCom1k', 'consPM_consComNWd_sum1k',
                         'consPM_consComNWd_avgAll1k', 'consPM_consComNWd_avgCom1k', 'consPM_consNCh_sum1k',
                         'consPM_consNCh_avgAll1k',
                         'consPM_consNCh_avgCom1k', 'consPM_consNCom_sum1k', 'consPM_consNCom_avgAll1k',
                         'consPM_consNCom_avgCom1k',
                         'consPM_consNSt_sum1k', 'consPM_consNSt_avgAll1k', 'consPM_consNSt_avgCom1k',
                         'consPM_consNWd_sum1k',
                         'consPM_consNWd_avgAll1k', 'consPM_consNWd_avgCom1k', 'advNum1k', 'advComNum1k',
                         'advP_simple1k',
                         'advP_advComNCh_sum1k', 'advP_advComNCh_avgAll1k', 'advP_advComNCh_avgCom1k',
                         'advP_advComNCom_sum1k',
                         'advP_advComNCom_avgAll1k', 'advP_advComNCom_avgCom1k', 'advP_advComNSt_sum1k',
                         'advP_advComNSt_avgAll1k',
                         'advP_advComNSt_avgCom1k', 'advP_advComNWd_sum1k', 'advP_advComNWd_avgAll1k',
                         'advP_advComNWd_avgCom1k',
                         'advP_advNCh_sum1k', 'advP_advNCh_avgAll1k', 'advP_advNCh_avgCom1k', 'advP_advNCom_sum1k',
                         'advP_advNCom_avgAll1k', 'advP_advNCom_avgCom1k', 'advP_advNSt_sum1k', 'advP_advNSt_avgAll1k',
                         'advP_advNSt_avgCom1k', 'advP_advNWd_sum1k', 'advP_advNWd_avgAll1k', 'advP_advNWd_avgCom1k',
                         'advPM_simple1k',
                         'advPM_advComNCh_sum1k', 'advPM_advComNCh_avgAll1k', 'advPM_advComNCh_avgCom1k',
                         'advPM_advComNCom_sum1k',
                         'advPM_advComNCom_avgAll1k', 'advPM_advComNCom_avgCom1k', 'advPM_advComNSt_sum1k',
                         'advPM_advComNSt_avgAll1k',
                         'advPM_advComNSt_avgCom1k', 'advPM_advComNWd_sum1k', 'advPM_advComNWd_avgAll1k',
                         'advPM_advComNWd_avgCom1k',
                         'advPM_advNCh_sum1k', 'advPM_advNCh_avgAll1k', 'advPM_advNCh_avgCom1k', 'advPM_advNCom_sum1k',
                         'advPM_advNCom_avgAll1k', 'advPM_advNCom_avgCom1k', 'advPM_advNSt_sum1k',
                         'advPM_advNSt_avgAll1k',
                         'advPM_advNSt_avgCom1k', 'advPM_advNWd_sum1k', 'advPM_advNWd_avgAll1k',
                         'advPM_advNWd_avgCom1k',
                         'allComNum1k', 'allP_simple1k', 'allP_allComNCh_sum1k', 'allP_allComNCh_avgAll1k',
                         'allP_allComNCh_avgCom1k',
                         'allP_allComNCom_sum1k', 'allP_allComNCom_avgAll1k', 'allP_allComNCom_avgCom1k',
                         'allP_allComNSt_sum1k',
                         'allP_allComNSt_avgAll1k', 'allP_allComNSt_avgCom1k', 'allP_allComNWd_sum1k',
                         'allP_allComNWd_avgAll1k',
                         'allP_allComNWd_avgCom1k', 'allP_allNCh_sum1k', 'allP_allNCh_avgAll1k', 'allP_allNCh_avgCom1k',
                         'allP_allNCom_sum1k', 'allP_allNCom_avgAll1k', 'allP_allNCom_avgCom1k', 'allP_allNSt_sum1k',
                         'allP_allNSt_avgAll1k', 'allP_allNSt_avgCom1k', 'allP_allNWd_sum1k', 'allP_allNWd_avgAll1k',
                         'allP_allNWd_avgCom1k', 'allPM_simple1k', 'allPM_allComNCh_sum1k', 'allPM_allComNCh_avgAll1k',
                         'allPM_allComNCh_avgCom1k', 'allPM_allComNCom_sum1k', 'allPM_allComNCom_avgAll1k',
                         'allPM_allComNCom_avgCom1k', 'allPM_allComNSt_sum1k', 'allPM_allComNSt_avgAll1k',
                         'allPM_allComNSt_avgCom1k',
                         'allPM_allComNWd_sum1k', 'allPM_allComNWd_avgAll1k', 'allPM_allComNWd_avgCom1k',
                         'allPM_allNCh_sum1k',
                         'allPM_allNCh_avgAll1k', 'allPM_allNCh_avgCom1k', 'allPM_allNCom_sum1k',
                         'allPM_allNCom_avgAll1k',
                         'allPM_allNCom_avgCom1k', 'allPM_allNSt_sum1k', 'allPM_allNSt_avgAll1k',
                         'allPM_allNSt_avgCom1k',
                         'allPM_allNWd_sum1k', 'allPM_allNWd_avgAll1k', 'allPM_allNWd_avgCom1k', 'ProsConsP_simple1k',
                         'ProsConsP_allComNCh_sum1k', 'ProsConsP_allComNCh_avgAll1k', 'ProsConsP_allComNCh_avgCom1k',
                         'ProsConsP_allComNCom_sum1k', 'ProsConsP_allComNCom_avgAll1k', 'ProsConsP_allComNCom_avgCom1k',
                         'ProsConsP_allComNSt_sum1k', 'ProsConsP_allComNSt_avgAll1k', 'ProsConsP_allComNSt_avgCom1k',
                         'ProsConsP_allComNWd_sum1k', 'ProsConsP_allComNWd_avgAll1k', 'ProsConsP_allComNWd_avgCom1k',
                         'ProsConsP_allNCh_sum1k', 'ProsConsP_allNCh_avgAll1k', 'ProsConsP_allNCh_avgCom1k',
                         'ProsConsP_allNCom_sum1k',
                         'ProsConsP_allNCom_avgAll1k', 'ProsConsP_allNCom_avgCom1k', 'ProsConsP_allNSt_sum1k',
                         'ProsConsP_allNSt_avgAll1k', 'ProsConsP_allNSt_avgCom1k', 'ProsConsP_allNWd_sum1k',
                         'ProsConsP_allNWd_avgAll1k', 'ProsConsP_allNWd_avgCom1k', 'ProsConsPM_simple1k',
                         'ProsConsPM_allComNCh_sum1k',
                         'ProsConsPM_allComNCh_avgAll1k', 'ProsConsPM_allComNCh_avgCom1k',
                         'ProsConsPM_allComNCom_sum1k',
                         'ProsConsPM_allComNCom_avgAll1k', 'ProsConsPM_allComNCom_avgCom1k',
                         'ProsConsPM_allComNSt_sum1k',
                         'ProsConsPM_allComNSt_avgAll1k', 'ProsConsPM_allComNSt_avgCom1k', 'ProsConsPM_allComNWd_sum1k',
                         'ProsConsPM_allComNWd_avgAll1k', 'ProsConsPM_allComNWd_avgCom1k', 'ProsConsPM_allNCh_sum1k',
                         'ProsConsPM_allNCh_avgAll1k', 'ProsConsPM_allNCh_avgCom1k', 'ProsConsPM_allNCom_sum1k',
                         'ProsConsPM_allNCom_avgAll1k', 'ProsConsPM_allNCom_avgCom1k', 'ProsConsPM_allNSt_sum1k',
                         'ProsConsPM_allNSt_avgAll1k', 'ProsConsPM_allNSt_avgCom1k', 'ProsConsPM_allNWd_sum1k',
                         'ProsConsPM_allNWd_avgAll1k', 'ProsConsPM_allNWd_avgCom1k', 'ProsConsAdvP_simple1k',
                         'ProsConsAdvP_allComNCh_sum1k', 'ProsConsAdvP_allComNCh_avgAll1k',
                         'ProsConsAdvP_allComNCh_avgCom1k',
                         'ProsConsAdvP_allComNCom_sum1k', 'ProsConsAdvP_allComNCom_avgAll1k',
                         'ProsConsAdvP_allComNCom_avgCom1k',
                         'ProsConsAdvP_allComNSt_sum1k', 'ProsConsAdvP_allComNSt_avgAll1k',
                         'ProsConsAdvP_allComNSt_avgCom1k',
                         'ProsConsAdvP_allComNWd_sum1k', 'ProsConsAdvP_allComNWd_avgAll1k',
                         'ProsConsAdvP_allComNWd_avgCom1k',
                         'ProsConsAdvP_allNCh_sum1k', 'ProsConsAdvP_allNCh_avgAll1k', 'ProsConsAdvP_allNCh_avgCom1k',
                         'ProsConsAdvP_allNCom_sum1k', 'ProsConsAdvP_allNCom_avgAll1k', 'ProsConsAdvP_allNCom_avgCom1k',
                         'ProsConsAdvP_allNSt_sum1k', 'ProsConsAdvP_allNSt_avgAll1k', 'ProsConsAdvP_allNSt_avgCom1k',
                         'ProsConsAdvP_allNWd_sum1k', 'ProsConsAdvP_allNWd_avgAll1k', 'ProsConsAdvP_allNWd_avgCom1k',
                         'ProsConsAdvPM_simple1k', 'ProsConsAdvPM_allComNCh_sum1k', 'ProsConsAdvPM_allComNCh_avgAll1k',
                         'ProsConsAdvPM_allComNCh_avgCom1k', 'ProsConsAdvPM_allComNCom_sum1k',
                         'ProsConsAdvPM_allComNSt_sum1k',
                         'ProsConsAdvPM_allComNSt_avgAll1k', 'ProsConsAdvPM_allComNSt_avgCom1k',
                         'ProsConsAdvPM_allComNWd_sum1k',
                         'ProsConsAdvPM_allComNWd_avgAll1k', 'ProsConsAdvPM_allComNWd_avgCom1k',
                         'ProsConsAdvPM_allNCh_sum1k',
                         'ProsConsAdvPM_allNCh_avgAll1k', 'ProsConsAdvPM_allNCh_avgCom1k',
                         'ProsConsAdvPM_allNCom_sum1k',
                         'ProsConsAdvPM_allNCom_avgAll1k', 'ProsConsAdvPM_allNCom_avgCom1k',
                         'ProsConsAdvPM_allNSt_sum1k',
                         'ProsConsAdvPM_allNSt_avgAll1k', 'ProsConsAdvPM_allNSt_avgCom1k', 'ProsConsAdvPM_allNWd_sum1k',
                         'ProsConsAdvPM_allNWd_avgAll1k', 'ProsConsAdvPM_allNWd_avgCom1k',
                         'ProsConsAdvPM_allComNCom_avAll1k',
                         'ProsConsAdvPM_allComNCom_avCom1k']


def generate_suffix_dict():
    n = 0
    suffix_dict = {}
    for i in independent_variables:
        if not i.startswith('pros') or 'PM' in i:
            continue

        suffix = '_'.join(i.split('_')[1:])[4:]

        for j in independent_variables:
            if j.endswith(suffix):
                if 'PM' in j:
                    key = 'PM_{}'.format(suffix)
                else:
                    key = 'P_{}'.format(suffix)
                if key not in suffix_dict:
                    suffix_dict[key] = []
                suffix_dict[key].append(j)
                n += 1

    print n


dep_vars = ['da', 'da_cfo', 'da_btm', 'absda', 'absda_cfo', 'absda_btm', 'da_win', 'da_win_cfo', 'da_win_btm',
            'absda_win', 'absda_win_cfo', 'absda_win_btm', 'da_ff48', 'da_ff48_cfo', 'da_ff48_btm', 'absda_ff48',
            'absda_ff48_cfo', 'absda_ff48_btm', 'da_ff48_win', 'da_ff48_win_cfo', 'da_ff48_win_btm', 'absda_ff48_win',
            'absda_ff48_win_cfo', 'absda_ff48_win_btm', 'resid', 'resid_loss', 'resid_loss_spi', 'resid_cfo',
            'absresid', 'absresid_loss', 'absresid_loss_spi', 'absresid_cfo', 'resid_std', 'resid_loss_std',
            'resid_lossspi_std', 'resid_cfo_std', 'resid_stddec', 'resid_loss_stddec', 'resid_lossspi_stddec',
            'resid_cfo_stddec', 'resid_win', 'resid_win_loss', 'resid_win_loss_spi', 'resid_win_cfo', 'absresid_win',
            'absresid_win_loss', 'absresid_win_loss_spi', 'absresid_win_cfo', 'resid_win_std', 'resid_win_loss_std',
            'resid_win_lossspi_std', 'resid_win_cfo_std', 'resid_win_stddec', 'resid_win_loss_stddec',
            'resid_win_lossspi_stddec', 'resid_win_cfo_stddec']

dd_dep_vars = ['resid', 'resid_loss', 'resid_loss_spi', 'resid_cfo', 'absresid', 'absresid_loss', 'absresid_loss_spi',
               'absresid_cfo', 'resid_std', 'resid_loss_std', 'resid_lossspi_std', 'resid_cfo_std', 'resid_stddec',
               'resid_loss_stddec', 'resid_lossspi_stddec', 'resid_cfo_stddec', 'resid_win', 'resid_win_loss',
               'resid_win_loss_spi', 'resid_win_cfo', 'absresid_win', 'absresid_win_loss', 'absresid_win_loss_spi',
               'absresid_win_cfo', 'resid_win_std', 'resid_win_loss_std', 'resid_win_lossspi_std', 'resid_win_cfo_std',
               'resid_win_stddec', 'resid_win_loss_stddec', 'resid_win_lossspi_stddec', 'resid_win_cfo_stddec']

da_dep_vars = ['da', 'da_cfo', 'da_btm', 'absda', 'absda_cfo', 'absda_btm', 'DA_win', 'absda_win', 'DA_win_cfo',
               'absda_win_cfo', 'DA_win_btm', 'absda_win_btm', 'DA_ff48', 'DA_ff48_cfo', 'DA_ff48_btm', 'absda_ff48',
               'absda_ff48_cfo', 'absda_ff48_btm', 'DA_ff48_win', 'absda_ff48_win', 'DA_ff48_win_cfo',
               'absda_ff48_win_cfo', 'DA_ff48_win_btm', 'absda_ff48_win_btm']

control_variables = ['oancf2at_std', 'sale2at_std', 'lnassets', 'loss_avg', 'sgrowth_chg', 'abvwret',
                     'litigation', 'foreign']
up_to_you = ['roa', 'cfo', 'accrual ', 'wc_chg', 'bleverage', 'sgrowth', 'no_intangible', 'cap_intensity',
             'restructure', 'age', 'btm', 'sale_chg', 'ibc_increase']
